name: sleep_timer
description: A sleep timer developed with flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+45

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  auto_route: ^0.6.9
  firebase_crashlytics: ^0.4.0+1
  flushbar: ^1.10.4
  get_it: ^5.0.6
  google_mobile_ads: ^0.11.0+2
  hue_dart: ^0.2.1
  in_app_purchase: ^0.3.5+1
  in_app_review: ^1.0.4
  injectable:
  introduction_screen: ^1.0.9
  json_annotation: ^3.1.1
  logger: ^0.9.4
  material_design_icons_flutter: ^4.0.5855
  observable_ish: ^2.1.5  
  preferences: ^5.2.1 
  provider: ^4.3.3
  shared_preferences: '>=0.5.12+4 <2.0.0'
  stacked: ^1.7.7
  stacked_services: ^0.7.2
  url_launcher: ^5.7.10
  
  device_functions:
    path: ../device_functions/
    # Add unpublished plugins from private repo
    # https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages
    # git:
    # url: git@github.com:drachim-dev/device_functions.git

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0
  path: ^1.8.0
  clock: ^1.1.0

dev_dependencies:
  auto_route_generator:
  build_runner:
  injectable_generator:
  json_serializable: ^3.5.1
  pedantic: ^1.10.0
  pigeon: ^0.1.20

flutter_intl:
  enabled: true

flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/intro/
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
