name: sleep_timer
description: A sleep timer developed with flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.7.1+11

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  auto_route: ^0.6.9
  flutter_native_admob: ^2.1.0+3
  get_it: ^5.0.1
  in_app_purchase: ^0.3.4+16
  injectable: 
  introduction_screen: ^1.0.9
  logger: ^0.9.4
  observable_ish:
  preferences: ^5.2.1
  provider: ^4.3.2+2
  shared_preferences: '>=0.5.12+4 <2.0.0'
  sleek_circular_slider: ^1.2.0+web
  stacked: ^1.7.6
  stacked_services: ^0.5.4+4
  url_launcher: ^5.7.10
  android_intent: '>=0.3.7+7 <2.0.0'
  spotify: ^0.4.0
  spotify_sdk: ^1.0.0
  webview_flutter: ^1.0.6
  flushbar: ^1.10.4
  
  device_functions:
    path: ../device_functions/
    # Add unpublished plugins from private repo
    # https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages
    # git:
      # url: git@github.com:FRiGiDiTy/device_functions.git

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  auto_route_generator:
  injectable_generator:
  build_runner:
  pigeon:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/intro/
    - assets/media_player/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
