// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class NotificationRequest {
  NotificationRequest({
    this.timerId,
    this.title,
    this.description,
    this.accentColor,
    this.restartAction,
    this.continueAction,
    this.pauseAction,
    this.cancelAction,
    this.extendActions,
  });

  String? timerId;

  String? title;

  String? description;

  int? accentColor;

  String? restartAction;

  String? continueAction;

  String? pauseAction;

  String? cancelAction;

  List<int?>? extendActions;

  Object encode() {
    return <Object?>[
      timerId,
      title,
      description,
      accentColor,
      restartAction,
      continueAction,
      pauseAction,
      cancelAction,
      extendActions,
    ];
  }

  static NotificationRequest decode(Object result) {
    result as List<Object?>;
    return NotificationRequest(
      timerId: result[0] as String?,
      title: result[1] as String?,
      description: result[2] as String?,
      accentColor: result[3] as int?,
      restartAction: result[4] as String?,
      continueAction: result[5] as String?,
      pauseAction: result[6] as String?,
      cancelAction: result[7] as String?,
      extendActions: (result[8] as List<Object?>?)?.cast<int?>(),
    );
  }
}

class TimeNotificationRequest {
  TimeNotificationRequest({
    this.description,
    this.timerId,
    this.title,
    this.accentColor,
    this.restartAction,
    this.continueAction,
    this.pauseAction,
    this.cancelAction,
    this.extendActions,
    this.duration,
    this.remainingTime,
  });

  String? description;

  String? timerId;

  String? title;

  int? accentColor;

  String? restartAction;

  String? continueAction;

  String? pauseAction;

  String? cancelAction;

  List<int?>? extendActions;

  /// The initial number of minutes the timer was set to.
  int? duration;

  /// The number of seconds left for the timer.
  int? remainingTime;

  Object encode() {
    return <Object?>[
      description,
      timerId,
      title,
      accentColor,
      restartAction,
      continueAction,
      pauseAction,
      cancelAction,
      extendActions,
      duration,
      remainingTime,
    ];
  }

  static TimeNotificationRequest decode(Object result) {
    result as List<Object?>;
    return TimeNotificationRequest(
      description: result[0] as String?,
      timerId: result[1] as String?,
      title: result[2] as String?,
      accentColor: result[3] as int?,
      restartAction: result[4] as String?,
      continueAction: result[5] as String?,
      pauseAction: result[6] as String?,
      cancelAction: result[7] as String?,
      extendActions: (result[8] as List<Object?>?)?.cast<int?>(),
      duration: result[9] as int?,
      remainingTime: result[10] as int?,
    );
  }
}

class RunningNotificationRequest {
  RunningNotificationRequest({
    this.description,
    this.timerId,
    this.title,
    this.accentColor,
    this.restartAction,
    this.continueAction,
    this.pauseAction,
    this.cancelAction,
    this.extendActions,
    this.duration,
    this.remainingTime,
    this.shakeToExtend,
  });

  String? description;

  String? timerId;

  String? title;

  int? accentColor;

  String? restartAction;

  String? continueAction;

  String? pauseAction;

  String? cancelAction;

  List<int?>? extendActions;

  int? duration;

  int? remainingTime;

  /// Enable shake to extend functionality.
  bool? shakeToExtend;

  Object encode() {
    return <Object?>[
      description,
      timerId,
      title,
      accentColor,
      restartAction,
      continueAction,
      pauseAction,
      cancelAction,
      extendActions,
      duration,
      remainingTime,
      shakeToExtend,
    ];
  }

  static RunningNotificationRequest decode(Object result) {
    result as List<Object?>;
    return RunningNotificationRequest(
      description: result[0] as String?,
      timerId: result[1] as String?,
      title: result[2] as String?,
      accentColor: result[3] as int?,
      restartAction: result[4] as String?,
      continueAction: result[5] as String?,
      pauseAction: result[6] as String?,
      cancelAction: result[7] as String?,
      extendActions: (result[8] as List<Object?>?)?.cast<int?>(),
      duration: result[9] as int?,
      remainingTime: result[10] as int?,
      shakeToExtend: result[11] as bool?,
    );
  }
}

class NotificationResponse {
  NotificationResponse({
    this.timerId,
    this.success,
  });

  String? timerId;

  bool? success;

  Object encode() {
    return <Object?>[
      timerId,
      success,
    ];
  }

  static NotificationResponse decode(Object result) {
    result as List<Object?>;
    return NotificationResponse(
      timerId: result[0] as String?,
      success: result[1] as bool?,
    );
  }
}

class CancelRequest {
  CancelRequest({
    this.timerId,
  });

  String? timerId;

  Object encode() {
    return <Object?>[
      timerId,
    ];
  }

  static CancelRequest decode(Object result) {
    result as List<Object?>;
    return CancelRequest(
      timerId: result[0] as String?,
    );
  }
}

class CancelResponse {
  CancelResponse({
    this.timerId,
    this.success,
  });

  String? timerId;

  bool? success;

  Object encode() {
    return <Object?>[
      timerId,
      success,
    ];
  }

  static CancelResponse decode(Object result) {
    result as List<Object?>;
    return CancelResponse(
      timerId: result[0] as String?,
      success: result[1] as bool?,
    );
  }
}

class ExtendTimeRequest {
  ExtendTimeRequest({
    this.timerId,
    this.additionalTime,
  });

  String? timerId;

  /// The time in seconds the timer was extended by.
  int? additionalTime;

  Object encode() {
    return <Object?>[
      timerId,
      additionalTime,
    ];
  }

  static ExtendTimeRequest decode(Object result) {
    result as List<Object?>;
    return ExtendTimeRequest(
      timerId: result[0] as String?,
      additionalTime: result[1] as int?,
    );
  }
}

class CountDownRequest {
  CountDownRequest({
    this.timerId,
    this.newTime,
  });

  String? timerId;

  /// The new time after countdown in seconds.
  int? newTime;

  Object encode() {
    return <Object?>[
      timerId,
      newTime,
    ];
  }

  static CountDownRequest decode(Object result) {
    result as List<Object?>;
    return CountDownRequest(
      timerId: result[0] as String?,
      newTime: result[1] as int?,
    );
  }
}

class OpenRequest {
  OpenRequest({
    this.timerId,
  });

  String? timerId;

  Object encode() {
    return <Object?>[
      timerId,
    ];
  }

  static OpenRequest decode(Object result) {
    result as List<Object?>;
    return OpenRequest(
      timerId: result[0] as String?,
    );
  }
}

class TimerRequest {
  TimerRequest({
    this.timerId,
  });

  String? timerId;

  Object encode() {
    return <Object?>[
      timerId,
    ];
  }

  static TimerRequest decode(Object result) {
    result as List<Object?>;
    return TimerRequest(
      timerId: result[0] as String?,
    );
  }
}

class WidgetUpdateResponse {
  WidgetUpdateResponse({
    this.title,
  });

  String? title;

  Object encode() {
    return <Object?>[
      title,
    ];
  }

  static WidgetUpdateResponse decode(Object result) {
    result as List<Object?>;
    return WidgetUpdateResponse(
      title: result[0] as String?,
    );
  }
}

class Package {
  Package({
    this.title,
    this.icon,
    this.packageName,
  });

  String? title;

  String? icon;

  String? packageName;

  Object encode() {
    return <Object?>[
      title,
      icon,
      packageName,
    ];
  }

  static Package decode(Object result) {
    result as List<Object?>;
    return Package(
      title: result[0] as String?,
      icon: result[1] as String?,
      packageName: result[2] as String?,
    );
  }
}

class InstalledAppsResponse {
  InstalledAppsResponse({
    this.apps,
  });

  List<Package?>? apps;

  Object encode() {
    return <Object?>[
      apps,
    ];
  }

  static InstalledAppsResponse decode(Object result) {
    result as List<Object?>;
    return InstalledAppsResponse(
      apps: (result[0] as List<Object?>?)?.cast<Package?>(),
    );
  }
}

class LaunchAppRequest {
  LaunchAppRequest({
    this.packageName,
  });

  String? packageName;

  Object encode() {
    return <Object?>[
      packageName,
    ];
  }

  static LaunchAppRequest decode(Object result) {
    result as List<Object?>;
    return LaunchAppRequest(
      packageName: result[0] as String?,
    );
  }
}

class ToggleRequest {
  ToggleRequest({
    this.enable,
  });

  bool? enable;

  Object encode() {
    return <Object?>[
      enable,
    ];
  }

  static ToggleRequest decode(Object result) {
    result as List<Object?>;
    return ToggleRequest(
      enable: result[0] as bool?,
    );
  }
}

class _HostTimerApiCodec extends StandardMessageCodec {
  const _HostTimerApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is CancelRequest) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is CancelResponse) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is InstalledAppsResponse) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is LaunchAppRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is NotificationRequest) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is NotificationResponse) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is Package) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is RunningNotificationRequest) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is TimeNotificationRequest) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is ToggleRequest) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return CancelRequest.decode(readValue(buffer)!);
      case 129: 
        return CancelResponse.decode(readValue(buffer)!);
      case 130: 
        return InstalledAppsResponse.decode(readValue(buffer)!);
      case 131: 
        return LaunchAppRequest.decode(readValue(buffer)!);
      case 132: 
        return NotificationRequest.decode(readValue(buffer)!);
      case 133: 
        return NotificationResponse.decode(readValue(buffer)!);
      case 134: 
        return Package.decode(readValue(buffer)!);
      case 135: 
        return RunningNotificationRequest.decode(readValue(buffer)!);
      case 136: 
        return TimeNotificationRequest.decode(readValue(buffer)!);
      case 137: 
        return ToggleRequest.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class HostTimerApi {
  /// Constructor for [HostTimerApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  HostTimerApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _HostTimerApiCodec();

  Future<NotificationResponse> showRunningNotification(RunningNotificationRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.sleep_timer.HostTimerApi.showRunningNotification', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as NotificationResponse?)!;
    }
  }

  Future<NotificationResponse> showPausingNotification(TimeNotificationRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.sleep_timer.HostTimerApi.showPausingNotification', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as NotificationResponse?)!;
    }
  }

  Future<NotificationResponse> showElapsedNotification(NotificationRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.sleep_timer.HostTimerApi.showElapsedNotification', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as NotificationResponse?)!;
    }
  }

  Future<CancelResponse> cancelTimer(CancelRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.sleep_timer.HostTimerApi.cancelTimer', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as CancelResponse?)!;
    }
  }

  Future<void> toggleExtendByShake(ToggleRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.sleep_timer.HostTimerApi.toggleExtendByShake', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<InstalledAppsResponse> getInstalledPlayerApps() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.sleep_timer.HostTimerApi.getInstalledPlayerApps', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as InstalledAppsResponse?)!;
    }
  }

  Future<InstalledAppsResponse> getInstalledAlarmApps() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.sleep_timer.HostTimerApi.getInstalledAlarmApps', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as InstalledAppsResponse?)!;
    }
  }

  Future<void> launchApp(LaunchAppRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.sleep_timer.HostTimerApi.launchApp', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}

class _FlutterTimerApiCodec extends StandardMessageCodec {
  const _FlutterTimerApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is CountDownRequest) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is ExtendTimeRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is OpenRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is TimerRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is WidgetUpdateResponse) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return CountDownRequest.decode(readValue(buffer)!);
      case 129: 
        return ExtendTimeRequest.decode(readValue(buffer)!);
      case 130: 
        return OpenRequest.decode(readValue(buffer)!);
      case 131: 
        return TimerRequest.decode(readValue(buffer)!);
      case 132: 
        return WidgetUpdateResponse.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class FlutterTimerApi {
  static const MessageCodec<Object?> codec = _FlutterTimerApiCodec();

  void onExtendTime(ExtendTimeRequest request);

  void onCountDown(CountDownRequest request);

  void onContinueRequest(TimerRequest request);

  void onPauseRequest(TimerRequest request);

  void onCancelRequest(TimerRequest request);

  void onRestartRequest(TimerRequest request);

  void onOpen(OpenRequest request);

  void onAlarm(TimerRequest request);

  WidgetUpdateResponse onWidgetUpdate();

  void onWidgetStartTimer();

  static void setup(FlutterTimerApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onExtendTime', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onExtendTime was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final ExtendTimeRequest? arg_request = (args[0] as ExtendTimeRequest?);
          assert(arg_request != null,
              'Argument for dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onExtendTime was null, expected non-null ExtendTimeRequest.');
          api.onExtendTime(arg_request!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onCountDown', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onCountDown was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final CountDownRequest? arg_request = (args[0] as CountDownRequest?);
          assert(arg_request != null,
              'Argument for dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onCountDown was null, expected non-null CountDownRequest.');
          api.onCountDown(arg_request!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onContinueRequest', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onContinueRequest was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final TimerRequest? arg_request = (args[0] as TimerRequest?);
          assert(arg_request != null,
              'Argument for dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onContinueRequest was null, expected non-null TimerRequest.');
          api.onContinueRequest(arg_request!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onPauseRequest', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onPauseRequest was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final TimerRequest? arg_request = (args[0] as TimerRequest?);
          assert(arg_request != null,
              'Argument for dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onPauseRequest was null, expected non-null TimerRequest.');
          api.onPauseRequest(arg_request!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onCancelRequest', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onCancelRequest was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final TimerRequest? arg_request = (args[0] as TimerRequest?);
          assert(arg_request != null,
              'Argument for dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onCancelRequest was null, expected non-null TimerRequest.');
          api.onCancelRequest(arg_request!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onRestartRequest', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onRestartRequest was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final TimerRequest? arg_request = (args[0] as TimerRequest?);
          assert(arg_request != null,
              'Argument for dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onRestartRequest was null, expected non-null TimerRequest.');
          api.onRestartRequest(arg_request!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onOpen', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onOpen was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final OpenRequest? arg_request = (args[0] as OpenRequest?);
          assert(arg_request != null,
              'Argument for dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onOpen was null, expected non-null OpenRequest.');
          api.onOpen(arg_request!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onAlarm', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onAlarm was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final TimerRequest? arg_request = (args[0] as TimerRequest?);
          assert(arg_request != null,
              'Argument for dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onAlarm was null, expected non-null TimerRequest.');
          api.onAlarm(arg_request!);
          return;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onWidgetUpdate', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          final WidgetUpdateResponse output = api.onWidgetUpdate();
          return output;
        });
      }
    }
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.sleep_timer.FlutterTimerApi.onWidgetStartTimer', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          // ignore message
          api.onWidgetStartTimer();
          return;
        });
      }
    }
  }
}
